steps:
  - script: deploy.sh
    env:
      GROUP_NAME: $(groupName)
      LOCATION: $(location)
      STORAGE_DEPLOYMENT_NAME: $(storageDeploymentName)
      VM_DEPLOYMENT_NAME: $(vmDeploymentName)
    displayName: "Run deploy shell script"
    
  - script: install-docker-ubuntu.sh
    env:
      GROUP_NAME: $(resourceGroupName)
      MACHINE_NAME: $(vmName)
    displayName: "Install Docker on VM"
    workingDirectory: utility-scripts