steps:
  - script: deploy.sh
    env:
      RESOURCE_GROUP: $(groupName)
      LOCATION: $(location)
      STORAGE_DEPLOYMENT_NAME: $(storageDeploymentName)
      VM_DEPLOYMENT_NAME: $(vmDeploymentName)
    displayName: "Run deploy shell script"
    
  - script: install-docker-ubuntu.sh
    env:
      MACHINE_NAME: $(vmName)
      Group_Name: $(resourceGroupName)
    displayName: "Install Docker on VM"
    workingDirectory: utility-scripts