steps:
  - script: deploy.sh
    env:
      resourceGroupName: $(groupName)
      location: $(location)
      storageDeploymentName: $(storageDeploymentName)
      vmDeploymentName: $(vmDeploymentName)
    displayName: "Run deploy shell script"
    
  - script: install-docker-ubuntu.sh
    env:
      machineName: $(vmName)
      resourceGroupName: $(resourceGroupName)
    displayName: "Install Docker on VM"
    workingDirectory: utility-scripts