steps:
  - script: deploy.sh
    env:
      GROUP_NAME: $(groupName)
      LOCATION: $(location)
      STORAGE_DEPLOYMENT_NAME: $(storageDeploymentName)
      VM_DEPLOYMENT_NAME: $(vmDeploymentName)
    displayName: "Run deploy shell script"
    
  - script: install-utilities.sh
    env:
      GROUP_NAME: $(resourceGroupName)
      MACHINE_NAME: $(vmName)
      displayName: "Install Utilities on VM"
    workingDirectory: utility-scripts
      
  - script: handle-blobs.sh
    env:
        GROUP_NAME: $(resourceGroupName)
        MACHINE_NAME: $(vmName)
        CONNECTION_STRING_A: $(CONNECTION_STRING_A)
        CONNECTION_STRING_B: $(CONNECTION_STRING_B)